### ISSUE TITLE
Add snippets for conditions

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#185]
When editing a YAML, user should be able to generate snippets for conditions using vscode code completion. The snippets are
* `Condition` type
* Condition reference in a taskref e.g.

```
    - name: list-pipeline-repo-files-1
      taskRef:
        name: list-pipeline-repo-files
      conditions:
        - conditionRef: "verify-no-file-exists-without-resource"
          params:
            - name: "path"
              value: "$(params.path)"
```
