### ISSUE TITLE
Error when starting pipeline with no spec/resource section

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/vscode-tekton#217]
If i try to start the pipeline below i get the following error. 

![image](https://user-images.githubusercontent.com/49404737/77420234-f5ec9c80-6dc9-11ea-8c45-8eec6779ab4b.png)

it fails here `context[0].resources.map<QuickPickItem>(label => ({ label: label.name }));`
```
spec:
  tasks:
  - name: tekton
    params:
    - name: ARGS
      value:
      - version
    taskRef:
      kind: Task
      name: openshift-client
```

**Comment by sudhirverma** [comment]
@lstocchi which yaml you use to create pipeline can you provide us full step to produce an error?

**Comment by lstocchi** [comment]
@sudhirverma just create a pipeline using the spec above and try to start it

```
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: blabla
spec:
  tasks:
  - name: tekton
    params:
    - name: ARGS
      value:
      - version
    taskRef:
      kind: Task
      name: openshift-client
```
