### ISSUE TITLE
Snippets ClusterTask wrong

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/vscode-tekton#225]
The snippet we have for ClusterTask is not in a correct form.
The current is:
```
apiVersion: tekton.dev/v1alpha1
kind: ClusterTask
metadata:
  name: foo
spec:
  steps:
  - args:
    - echo clustertask
```
but if you try to create the resource in the cluster you face this error
```
Error from server (InternalError): error when creating "/home/luca/Documents/f.yaml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: missing field(s): steps.Image
```

A possible alternative could be:
```
spec:
  steps:
  - image: ubuntu
    script: |
      #!/usr/bin/env bash
      echo "Hello"
```

As always this is a minor issue but i think we should show a working snippets, so people who start using the extension and have no experience with Tekton can play and learn with it
