### ISSUE TITLE
Display param descriptions in start pipeline and add trigger

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-tekton#413]
"Start pipeline" and "add trigger" form should display the param descriptions to help understand the parameters

```
  params:
  - default: nodejs-ex-git
    description: Application Name
    name: APP_NAME
    type: string
```

Currently only name is displayed:

<img width="500" alt="Screenshot 2020-10-01 at 14 07 02" src="https://user-images.githubusercontent.com/1174934/94807141-821df300-03ef-11eb-86ca-1ec15b37ddd9.png">
