### ISSUE TITLE
Incorrect workflow when finally clauses

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/vscode-tekton#424]
Given the follwing pipeline:
```

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: workflow
spec:
  finally:
  - name: cleanup
    taskRef:
      kind: Task
      name: echo
  - name: cleanup1
    taskRef:
      kind: Task
      name: echo
    runAfter:
      - cleanup
  tasks:
  - conditions:
    - conditionRef: always-true
    name: always-echo
    taskRef:
      kind: Task
      name: echo
  - conditions:
    - conditionRef: always-false
    name: never-echo
    taskRef:
      kind: Task
      name: echo
  - name: echo
    taskRef:
      kind: Task
      name: echo
```

The representation is the following:

![image](https://user-images.githubusercontent.com/695993/95713758-632d2580-0c67-11eb-815f-8878c4d7fa00.png)

There are several issues:
- the finally tasks should be linked to **always-echo** and **never-echo** tasks as well
- task **cleanup1** should be executed after **cleanup**
- there is a warning on the **runAfter** field to cleanup: `Value is not accepted. Valid values: "always-echo", "never-echo", "echo".`
