### ISSUE TITLE
Wrong behavior in Tekton Hub when uninstalling resources

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/vscode-tekton#515]
A couple of thoughts on the tekton hub.
1) The first is an enhancement. I have installed the `aws-cli` task in my cluster as `task` and `clustertask`. If i want to uninstall it from vscode i don't know which one i'm uninstalling. Maybe we could add a label/flag/icon to tell the user "this is the clustertask/this is the task"

![image](https://user-images.githubusercontent.com/49404737/109792402-c407cb00-7c13-11eb-8ff5-4a51417074c5.png)

2) The second is a wrong behavior. Let's say i installed the hub task `buildpacks` as clustertask in my cluster. And i also have a task with the same name but it is not installed from the hub. Something like 
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildpacks
spec:
  steps:
    - name: build-sources
      image: fedora
      command: 
      - /bin/bash
      args: ['-c', 'echo hello world']
```

In the list of installed resources, everything looks fine as i only see one `buildpacks` item but if i try to uninstall it, my task gets deleted which is wrong as this is not the hub item.
