### ISSUE TITLE
Property apiVersion is not allowed in TriggerTemplate

### ISSUE THREAD

**Issue by b1zzu** [redhat-developer/vscode-tekton#553]
This is my TriggerTemplate:
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-configuration-cd
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        generateName: tekton-configuration-cd-
      spec:
        taskRef:
          name: tekton-configuration-cd
        resources:
          inputs:
            - name: tekton-configuration-git
              resourceRef:
                name: tekton-configuration-git
```
and I double-check it with the documentation multiple times and is correct, but on vs code with the tekton extension I see this error:
![image](https://user-images.githubusercontent.com/7964685/114158629-319acb80-9925-11eb-8faa-40766c2cec5d.png)

Tekton Pipelines: v0.13.0
